# Generated by Django 5.2.6 on 2025-09-03 13:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140, unique=True)),
                ("balance", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["balance"], name="credits_wal_balance_17ae02_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("label", models.CharField(blank=True, max_length=140)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="credits.wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta", models.BigIntegerField()),
                (
                    "tx_type",
                    models.CharField(
                        choices=[
                            ("debit", "Debit"),
                            ("credit", "Credit"),
                            ("refund", "Refund"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "tx_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("committed", "Committed"),
                            ("reversed", "Reversed"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("request_id", models.CharField(blank=True, max_length=64, null=True)),
                ("note", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="credits.wallet",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["wallet", "created_at"],
                        name="credits_cre_wallet__4e2306_idx",
                    ),
                    models.Index(
                        fields=["idempotency_key"],
                        name="credits_cre_idempot_0b72dd_idx",
                    ),
                ],
                "unique_together": {("wallet", "idempotency_key")},
            },
        ),
    ]
