# Generated by Django 5.2.6 on 2025-09-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="credittransaction",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="credittransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", None), _negated=True),
                fields=("wallet", "idempotency_key"),
                name="unique_wallet_idempotency_key_not_null",
            ),
        ),
    ]
